### ISSUE TITLE
Where can download the pre-trained model for HRnet？

### ISSUE THREAD

**Issue by zytx121** [CaoWGG/torch-yolov3#1]
Thx！

**Comment by CaoWGG** [comment]
hrnet的预训练权重可以从这下载
链接：https://pan.baidu.com/s/1h752hE8DTaEm_6DyNO5LIw 
提取码：b50t 
或者从
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch 下载

**Comment by CaoWGG** [comment]
> Thx！

hrnet的预训练权重可以从这下载
链接：https://pan.baidu.com/s/1h752hE8DTaEm_6DyNO5LIw
提取码：b50t
或者从
https://github.com/leoxiaobin/deep-high-resolution-net.pytorch 下载

**Comment by zytx121** [comment]
thank you ！
